class ActionTypes {
  static const ADD_PAYMENT_REQ = 'ADD_PAYMENT_REQ';
  static const ADD_PAYMENT_SUCCESS = 'ADD_PAYMENT_SUCCESS';
  static const ADD_PAYMENT_FAILURE = 'ADD_PAYMENT_FAILURE';

  static const DELETE_PAYMENT_REQ = 'DELETE_PAYMENT_REQ';
  static const DELETE_PAYMENT_SUCCESS = 'DELETE_PAYMENT_SUCCESS';
  static const DELETE_PAYMENT_FAILURE = 'DELETE_PAYMENT_FAILURE';

  static const UPDATE_PAYMENT_REQ = 'UPDATE_PAYMENT_REQ';
  static const UPDATE_PAYMENT_SUCCESS = 'UPDATE_PAYMENT_SUCCESS';
  static const UPDATE_PAYMENT_FAILURE = 'UPDATE_PAYMENT_FAILURE';

  static const LOAD_PAYMENT_REQ = 'LOAD_PAYMENT_REQ';
  static const LOAD_PAYMENT_SUCCESS = 'LOAD_PAYMENT_SUCCESS';
  static const LOAD_PAYMENT_FAILURE = 'LOAD_PAYMENT_FAILURE';

  static const LOAD_ALL_PAYMENTS_REQ = 'LOAD_ALL_PAYMENTS_REQ';
  static const LOAD_ALL_PAYMENTS_SUCCESS = 'LOAD_ALL_PAYMENTS_SUCCESS';
  static const LOAD_ALL_PAYMENTS_FAILURE = 'LOAD_ALL_PAYMENTS_FAILURE';

  static const LOAD_SELECTED_USER_PURCHASES_REQ = 'LOAD_SELECTED_USER_PURCHASES_REQ';
  static const LOAD_SELECTED_USER_PURCHASES_SUCCESS = 'LOAD_SELECTED_USER_PURCHASES_SUCCESS';
  static const LOAD_SELECTED_USER_PURCHASES_FAILURE = 'LOAD_SELECTED_USER_PURCHASES_FAILURE';

  static const LOAD_SELECTED_USER_PAYMENTS_REQ = 'LOAD_SELECTED_USER_PAYMENTS_REQ';
  static const LOAD_SELECTED_USER_PAYMENTS_SUCCESS = 'LOAD_SELECTED_USER_PAYMENTS_SUCCESS';
  static const LOAD_SELECTED_USER_PAYMENTS_FAILURE = 'LOAD_SELECTED_USER_PAYMENTS_FAILURE';
}
