class ActionTypes {
  static const ADD_USER_REQ = 'ADD_USER_REQ';
  static const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
  static const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

  static const UPDATE_USER_REQ = 'UPDATE_USER_REQ';
  static const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
  static const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

  static const DELETE_USER_REQ = 'DELETE_USER_REQ';
  static const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
  static const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

  static const LOAD_ALL_USERS_REQ = 'LOAD_ALL_USERS_REQ';
  static const LOAD_ALL_USERS_SUCCESS = 'LOAD_ALL_USERS_SUCCESS';
  static const LOAD_ALL_USERS_FAILURE = 'LOAD_ALL_USERS_FAILURE';

  static const LOAD_SELECTED_USER_REQ = 'LOAD_SELECTED_USER_REQ';
  static const LOAD_SELECTED_USER_SUCCESS = 'LOAD_SELECTED_USER_SUCCESS';
  static const LOAD_SELECTED_USER_FAILURE = 'LOAD_SELECTED_USER_FAILURE';
}
